import type { Metadata, Viewport } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'

/**
 * Lato font for all typography (headings and body).
 * A clean, professional humanist sans-serif with excellent readability.
 * Works well at all sizes from body text to large display headlines.
 * Weight 300 for light/subtle text, 400 for body, 700 for emphasis/headings, 900 for display.
 */
const lato = Lato({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato',
  weight: ['300', '400', '700', '900'],
  preload: true,
})

/**
 * Viewport configuration for mobile devices.
 * maximumScale: 5 allows users to zoom for accessibility (WCAG compliance).
 * The previous value of 1 prevented zooming which is an accessibility issue.
 */
export const viewport: Viewport = {
  themeColor: '#07675e',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
}

/**
 * Site metadata configuration for SEO and social sharing.
 * 
 * OpenGraph and Twitter images are automatically generated by:
 * - src/app/opengraph-image.tsx (for og:image)
 * - src/app/twitter-image.tsx (for twitter:image)
 * 
 * Next.js automatically detects these files and generates the appropriate meta tags.
 */
export const metadata: Metadata = {
  metadataBase: new URL('https://sleekdentalclub.com'),
  title: 'SLEEK Dental | A Dental Experience Worth Smiling About',
  description: 'SLEEK Dental offers affordable dental care memberships with electric toothbrush kits and value-added benefits for individuals and families.',
  icons: {
    icon: [
      {
        url: '/images/SLEEK-Favicon.png',
        type: 'image/png',
      },
    ],
    apple: {
      url: '/images/SLEEK-Favicon.png',
      type: 'image/png',
    },
  },
  openGraph: {
    title: 'SLEEK Dental | A Dental Experience Worth Smiling About',
    description: 'Affordable dental care memberships with electric toothbrush kits and more.',
    url: 'https://sleekdentalclub.com',
    siteName: 'SLEEK Dental',
    // Images are auto-generated by src/app/opengraph-image.tsx
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SLEEK Dental | A Dental Experience Worth Smiling About',
    description: 'Affordable dental care memberships with electric toothbrush kits and more.',
    // Images are auto-generated by src/app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`scroll-smooth ${lato.variable}`}>
      <head>
        {/* Preload critical hero image for faster LCP */}
        <link
          rel="preload"
          href="/images/SleekKit.jpg"
          as="image"
          type="image/jpeg"
        />
      </head>
      <body className="min-h-screen bg-white font-body antialiased selection:bg-teal-200 selection:text-teal-900">
        {/* Global grain texture overlay for premium feel */}
        <div className="grain-overlay" aria-hidden="true" />
        
        <div className="relative overflow-hidden">
          {/* Enhanced ambient background gradient shapes */}
          <div className="fixed inset-0 overflow-hidden pointer-events-none z-[-1]">
            <div className="absolute -top-[30%] -left-[10%] w-[50%] h-[60%] rounded-full bg-gradient-to-br from-teal-100/40 to-teal-50/20 blur-3xl animate-pulse-slow" />
            <div className="absolute top-[20%] -right-[20%] w-[70%] h-[40%] rounded-full bg-gradient-to-bl from-teal-100/30 to-teal-50/20 blur-3xl" />
            <div className="absolute -bottom-[10%] left-[20%] w-[60%] h-[40%] rounded-full bg-gradient-to-tr from-teal-100/30 to-transparent blur-3xl" />
          </div>
          {children}
        </div>
      </body>
    </html>
  )
} 